name: breast

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - openjdk=17

  - pip

  # Data Processing
  - numpy
  - pandas
  - scipy
  - pyarrow
  - openpyxl

  # Visualization
  - matplotlib
  - seaborn

  # Machine Learning
  - scikit-learn

  # Notebook
  - jupyterlab
  - notebook
  - ipykernel

  # Utilities
  - pyyaml
  - tqdm

  - pip:
      - pyspark==3.5.6